### PR TITLE
Implement popToRoot command

### LINKED ISSUE #3: unknown nav command type "popToRoot"
unknown nav command {type: "popToRoot"}

### PR DESCRIPTION
**Pull request by Powersource**
Fixes https://github.com/staltz/cycle-native-navigation-web/issues/3

hopefully

### CODE REVIEW

**Comment by staltz** [comment]
Looks good! I'll merge when I'm also by my computer and could make a new release

**Comment by Powersource** [comment]
Didn't manage to test this fwiw

(is there some good writeup on how to use library forks in apps?)

**Comment by staltz** [comment]
I sometimes just compile the TS to JS and copy paste it to my node_modules library

**Comment by staltz** [comment]
Other times I do this in package.json

```
  "react": "staltz/react#foobar"
```

To use my fork of react on GitHub (the use of github is implicit in that) on the branch foobar

**Comment by staltz** [comment]
version 0.6.0

**Comment by Powersource** [comment]
> I sometimes just compile the TS to JS and copy paste it to my node_modules library

yeah that's basically what npm link helps you do right? I tried that a few days ago but ran into problems with (peer)dependencies or something

> Other times I do this in package.json

I tried this yesterday with this branch (but using a direct git link) but that didn't work, the only things that ended up installed from the module were `LICENSE  package.json  README.md`, I'm guessing because npmignore ignores `src`

**Comment by staltz** [comment]
> the only things that ended up installed from the module were `LICENSE package.json README.md`, I'm guessing because npmignore ignores `src`

I think you needed to compile the typescript with `npm run compile`, which would generate the `lib` folder and `lib` is not npm ignored, it would be shipped

**Pull request merged**
